### PR TITLE
Updated for commonjs support

### PR DESCRIPTION
**Pull request by lostpebble**
#16 As per issue, added an index.js (as it's the default npm module file) which references the geolocator library, which I changed slightly so that it exports a commonjs module (on top of its usual functionality).

### CODE REVIEW

**Comment by hampsterx** [comment]
*bump* this would be nice thnx~

**Comment by onury** [comment]
Thanks but this is already covered in the upcoming (v2.0) release which is a complete re-write and will be released shortly.

**Comment by hampsterx** [comment]
@onury any progress on the rewrite?

**Comment by onury** [comment]
version 2 is released with CommonJS support.
Thanks.

**Pull request closed without merging**
