### PR TITLE
Adds cookie management capabilities for enhanced performance

### PR DESCRIPTION
**Pull request by Quasso**
Hey Onur, 

I recently stumbled upon your script after seeing a comment you'd posted on Stackoverflow--it's great and it really helped speed up something I was working on with a website. One thing I ended up doing was some trickery with cookies, because I tend to be quite obsessive about performance and having analysed results via GTMetrix I noticed additional DNS lookups, not to mention the inherent variability and delay in getting the results. For localisation purposes, the faster the better (of course!) I got an average of around 600ms, and although relatively fast, if a user were to load a page part-way down, there's a possibility they wouldn't see certain contain properly tuned to them for a small time.

Either way, I think this is quite a useful addition/feature, I haven't spent very long writing it and I've done some testing--everything seems fine. There are new parameters allowing the developer to disable the cookie management, but I'm hard pushed to see why one would want to do that.

Let me know what you think!

### CODE REVIEW

**Comment by Quasso** [comment]
Dang, I just saw your comment in the other pull request saying you're re-writing. This may be redundant--but if you think this'd be useful within the rewrite, I'd happily help incorporate it. Either way, great work!

**Comment by onury** [comment]
@Quasso Yes I'm re-writing. Thanks for your input, though. But I think cache logic should exist within the app not in a utility like this. Besides, I don't need caching is necessary since I would re-locate only when I need to get fresh coordinates.

**Comment by Quasso** [comment]
@onury, I guess it's just a matter of preference, I personally would prefer a utility to handle it well on a basic level with some customisation options. The two things you mentioned essentially condense into the same point because they both require writing some means of recording when the function should be triggered again. The latter I guess is actually more complicated because how do you know when you ought to update for fresh co-ordinates without checking their current location? The simplest way I can think of is when their IP changes, though it may trigger undesirably.

To be honest, as soon as I discovered you're re-writing with the ability to _not_ load GMaps, it essentially rendered my motivation for making this redundant anyway!

Look forward to the new release, if you'd like any contributors I may be able to help :)

**Comment by onury** [comment]
@Quasso, what I meant was; caching belongs to a separate logic that the app as a whole could benefit from. A separate utility plugged-in to the app could do the caching for location too.

v2 is written in ES6 (ES2015) and built via webpack+babel into ES5. Once it's released, I'd of course welcome any kind of contribution. Thanks again for your interest.

**Comment by Quasso** [comment]
@onury, I do see what you mean. It really depends on the use case.. I'm not using it within an application, it's a website, hence my inclination toward thinking that would be useful--the extra bloat of a new utility wouldn't be worth it since I have no other use for caching. For web apps, I do indeed agree you'd want finer-grained control and you _should_ already be implementing caching for other things. 

I'll keep an eye on it, if I feel I can help (more whether I have time) I will do. On a similar topic, do you plan on making V2 available as a dedicated Angular module? If you hadn't planned on it, I could maybe help there.

Thanks again for making this :)

**Pull request closed without merging**
